[build]
  publish = "."
  command = ""

[build.environment]
  DISABLE_PYTHON_BUILDS = "true"

# Disable Netlify script injection
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = false
  minify = false

[build.processing.js]
  bundle = false
  minify = false

[build.processing.html]
  pretty_urls = true

# Headers to prevent script injection
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Disable Netlify analytics and injection
[template.environment]
  NETLIFY_USE_EDGE_HANDLERS = "false"

# Prevent automatic script injection
[context.production.environment]
  NETLIFY_SKIP_FORMS_PROCESSING = "true"